# Generated by Django 2.2.5 on 2020-01-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
