# Generated by Django 2.2.9 on 2020-01-22 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progressApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='title',
            field=models.CharField(default='test title', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
