# Generated by Django 2.2.9 on 2020-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressApi', '0002_auto_20200122_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='data',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='progress',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
