# Generated by Django 2.2.9 on 2020-02-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsawaiting',
            name='button_text',
            field=models.CharField(blank=True, default='Send Request', max_length=20),
        ),
    ]
