# Generated by Django 2.2.9 on 2020-02-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_connectionsawaiting_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionsawaiting',
            name='button_text',
        ),
    ]
