# Generated by Django 2.2.9 on 2020-02-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200208_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
